import { v4 as uuidv4 } from 'uuid';
import { CryptoFinding, ScanResult } from '../types';

// CycloneDX algorithm primitive types
const PRIMITIVE_MAP: Record<string, string> = {
  'sha': 'hash',
  'sha-': 'hash',
  'md5': 'hash',
  'md4': 'hash',
  'sha1': 'hash',
  'sha2': 'hash',
  'sha3': 'hash',
  'ripemd': 'hash',
  'hmac': 'mac',
  'cmac': 'mac',
  'gmac': 'mac',
  'poly': 'mac',
  'aes': 'blockCipher',
  'des': 'blockCipher',
  '3des': 'blockCipher',
  'chacha': 'streamCipher',
  'rc4': 'streamCipher',
  'rsa': 'pke',
  'ecdsa': 'signature',
  'eddsa': 'signature',
  'dsa': 'signature',
  'ecdh': 'keyAgreement',
  'dh': 'keyAgreement',
  'x25519': 'keyAgreement',
  'x448': 'keyAgreement',
  'pbkdf2': 'kdf',
  'scrypt': 'kdf',
  'bcrypt': 'kdf',
  'argon2': 'kdf',
  'hkdf': 'kdf',
  'csprng': 'prf',
  'tls': 'protocol',
  'jwt': 'protocol',
  'hardcoded': 'other',
  'math-random': 'prf',
  'date-now': 'other',
  'cipher-suite': 'protocol'
};

// Known OIDs for common algorithms
const OID_MAP: Record<string, string> = {
  'MD5': '1.2.840.113549.2.5',
  'SHA-1': '1.3.14.3.2.26',
  'SHA-256': '2.16.840.1.101.3.4.2.1',
  'SHA-384': '2.16.840.1.101.3.4.2.2',
  'SHA-512': '2.16.840.1.101.3.4.2.3',
  'AES-128': '2.16.840.1.101.3.4.1.1',
  'AES-256': '2.16.840.1.101.3.4.1.41',
  'RSA': '1.2.840.113549.1.1.1',
  'ECDSA': '1.2.840.10045.4.3.2',
  'DES': '1.3.14.3.2.7',
  'PBKDF2': '1.2.840.113549.1.5.12'
};

export interface CycloneDXCBOM {
  bomFormat: 'CycloneDX';
  specVersion: '1.6';
  serialNumber: string;
  version: number;
  metadata: object;
  components: object[];
  vulnerabilities?: object[];
}

export function generateCBOM(scanResult: ScanResult): CycloneDXCBOM {
  const { findings, projectName, projectPath, summary } = scanResult;

  return {
    bomFormat: 'CycloneDX',
    specVersion: '1.6',
    serialNumber: `urn:uuid:${uuidv4()}`,
    version: 1,
    metadata: buildMetadata(projectName, projectPath, scanResult),
    components: findings.map(f => buildComponent(f, projectPath)),
    ...(hasVulnerabilities(findings) ? {
      vulnerabilities: buildVulnerabilities(findings)
    } : {})
  };
}

function buildMetadata(projectName: string, projectPath: string, scan: ScanResult): object {
  return {
    timestamp: new Date().toISOString(),
    tools: [
      {
        vendor: 'cbom-js',
        name: 'cbom-js',
        version: '1.0.0',
        externalReferences: [
          {
            type: 'website',
            url: 'https://github.com/your-org/cbom-js'
          }
        ]
      }
    ],
    component: {
      type: 'application',
      'bom-ref': `pkg:generic/${projectName}@1.0.0`,
      name: projectName,
      version: '1.0.0',
      description: `CBOM generated by cbom-js for ${projectName}`
    },
    properties: [
      { name: 'cbom-js:filesScanned', value: String(scan.filesScanned) },
      { name: 'cbom-js:scanDuration', value: `${scan.duration}ms` },
      { name: 'cbom-js:totalFindings', value: String(scan.summary.total) },
      { name: 'cbom-js:criticalFindings', value: String(scan.summary.critical) },
      { name: 'cbom-js:highFindings', value: String(scan.summary.high) },
      { name: 'cbom-js:weakAlgorithms', value: String(scan.summary.weak) },
      { name: 'cbom-js:quantumVulnerable', value: String(scan.summary.quantumVulnerable) },
      { name: 'cbom-js:sourcePath', value: projectPath }
    ]
  };
}

function buildComponent(finding: CryptoFinding, rootPath: string): object {
  const primitive = derivePrimitive(finding.algorithm);
  const oid = deriveOID(finding.algorithm);

  const component: Record<string, unknown> = {
    type: 'cryptoAsset',
    'bom-ref': `crypto:${finding.algorithm.toLowerCase()}:${finding.location.replace(rootPath, '')}:${finding.line}`,
    name: finding.algorithm,
    cryptoProperties: {
      assetType: 'algorithm',
      algorithmProperties: {
        primitive,
        ...(finding.mode ? { mode: finding.mode.toLowerCase() } : {}),
        ...(finding.keySize ? { parameterSetIdentifier: String(finding.keySize) } : {}),
        executionEnvironment: 'software',
        implementationPlatform: 'node.js',
        certificationLevel: ['none'],
        cryptoFunctions: deriveCryptoFunctions(primitive),
        nistQuantumSecurityLevel: finding.quantumSafe ? 1 : 0,
        classicalSecurityLevel: deriveClassicalSecurity(finding.algorithm, finding.keySize)
      },
      ...(oid ? { oid } : {})
    },
    evidence: {
      occurrences: [
        {
          location: finding.location.replace(rootPath + '/', ''),
          line: finding.line,
          ...(finding.column !== undefined ? { offset: finding.column } : {}),
          symbol: finding.algorithm
        }
      ]
    },
    properties: [
      { name: 'cbom-js:library', value: finding.library },
      { name: 'cbom-js:weak', value: String(finding.weak) },
      { name: 'cbom-js:quantumSafe', value: String(finding.quantumSafe) },
      { name: 'cbom-js:severity', value: finding.severity },
      ...(finding.cwe && finding.cwe.length > 0
        ? finding.cwe.map(c => ({ name: 'cbom-js:cwe', value: c }))
        : []),
      ...(finding.notes ? [{ name: 'cbom-js:notes', value: finding.notes }] : []),
      ...(finding.context ? [{ name: 'cbom-js:codeSnippet', value: finding.context }] : [])
    ]
  };

  return component;
}

function buildVulnerabilities(findings: CryptoFinding[]): object[] {
  const vulns: object[] = [];

  for (const f of findings) {
    if (!f.weak && f.severity === 'INFO') continue;
    if (!f.cwe || f.cwe.length === 0) continue;

    vulns.push({
      'bom-ref': `vuln:${f.algorithm}:${f.location}:${f.line}`,
      id: f.cwe[0],
      source: {
        name: 'CWE',
        url: `https://cwe.mitre.org/data/definitions/${f.cwe[0].replace('CWE-', '')}.html`
      },
      ratings: [
        {
          severity: f.severity.toLowerCase(),
          method: 'other'
        }
      ],
      description: buildVulnDescription(f),
      affects: [
        {
          ref: `crypto:${f.algorithm.toLowerCase()}:${f.location}:${f.line}`
        }
      ]
    });
  }

  return vulns;
}

function buildVulnDescription(finding: CryptoFinding): string {
  if (finding.notes) return finding.notes;

  if (finding.algorithm.includes('MD5')) return 'MD5 is a cryptographically broken hash function vulnerable to collision attacks';
  if (finding.algorithm.includes('SHA1') || finding.algorithm.includes('SHA-1')) return 'SHA-1 is deprecated and vulnerable to collision attacks';
  if (finding.algorithm.includes('RC4')) return 'RC4 stream cipher is broken and must not be used';
  if (finding.algorithm.includes('DES') && !finding.algorithm.includes('3DES')) return 'DES has a 56-bit key size which is computationally breakable';
  if (finding.algorithm.includes('ECB')) return 'ECB mode does not provide semantic security and leaks data patterns';
  if (!finding.quantumSafe) return `${finding.algorithm} is vulnerable to quantum computing attacks (Shor\'s algorithm)`;

  return `Weak or deprecated cryptographic algorithm: ${finding.algorithm}`;
}

function derivePrimitive(algorithm: string): string {
  const algo = algorithm.toLowerCase();
  for (const [prefix, primitive] of Object.entries(PRIMITIVE_MAP)) {
    if (algo.startsWith(prefix) || algo.includes(prefix)) {
      return primitive;
    }
  }
  return 'other';
}

function deriveOID(algorithm: string): string | null {
  const algo = algorithm.toUpperCase();
  for (const [key, oid] of Object.entries(OID_MAP)) {
    if (algo === key || algo.startsWith(key)) return oid;
  }
  return null;
}

function deriveCryptoFunctions(primitive: string): string[] {
  const map: Record<string, string[]> = {
    'hash': ['digest'],
    'mac': ['generate', 'verify'],
    'blockCipher': ['encrypt', 'decrypt'],
    'streamCipher': ['encrypt', 'decrypt'],
    'pke': ['encapsulate', 'decapsulate'],
    'signature': ['sign', 'verify'],
    'keyAgreement': ['keyDerive'],
    'kdf': ['keyDerive'],
    'prf': ['generate'],
    'protocol': ['authenticate', 'keyDerive'],
    'other': []
  };
  return map[primitive] || [];
}

function deriveClassicalSecurity(algorithm: string, keySize?: number): number {
  const algo = algorithm.toLowerCase();

  // Hash-based security
  if (algo.includes('sha-256') || algo.includes('sha256')) return 128;
  if (algo.includes('sha-512') || algo.includes('sha512')) return 256;
  if (algo.includes('sha-1') || algo.includes('sha1')) return 0; // broken
  if (algo.includes('md5')) return 0; // broken

  // Symmetric
  if (keySize === 128) return 128;
  if (keySize === 256) return 256;
  if (keySize === 192) return 192;

  // Asymmetric
  if (algo.includes('rsa')) {
    if (!keySize) return 112;
    if (keySize >= 4096) return 140;
    if (keySize >= 2048) return 112;
    return 0; // below 2048 = broken
  }

  return 128; // default assumption
}

function hasVulnerabilities(findings: CryptoFinding[]): boolean {
  return findings.some(f => f.weak || f.cwe && f.cwe.length > 0);
}