import { v4 as uuidv4 } from 'uuid';
import { CryptoFinding, ScanResult } from '../types';
import { getAlgorithmMeta } from '../registry/registryLoader';

export interface CycloneDXCBOM {
  bomFormat: 'CycloneDX';
  specVersion: '1.6';
  serialNumber: string;
  version: number;
  metadata: object;
  components: object[];
  vulnerabilities?: object[];
}

export function generateCBOM(scanResult: ScanResult): CycloneDXCBOM {
  const { findings, projectName, projectPath, summary } = scanResult;

  return {
    bomFormat: 'CycloneDX',
    specVersion: '1.6',
    serialNumber: `urn:uuid:${uuidv4()}`,
    version: 1,
    metadata: buildMetadata(projectName, projectPath, scanResult),
    components: findings.map(f => buildComponent(f, projectPath)),
    ...(hasVulnerabilities(findings) ? {
      vulnerabilities: buildVulnerabilities(findings)
    } : {})
  };
}

// ── Metadata ──────────────────────────────────────────────────────────────────

function buildMetadata(projectName: string, projectPath: string, scan: ScanResult): object {
  return {
    timestamp: new Date().toISOString(),
    tools: [
      {
        vendor: 'cbom-js',
        name: 'cbom-js',
        version: '1.0.0',
        externalReferences: [
          { type: 'website', url: 'https://github.com/your-org/cbom-js' }
        ]
      }
    ],
    component: {
      type: 'application',
      'bom-ref': `pkg:generic/${projectName}@1.0.0`,
      name: projectName,
      version: '1.0.0',
      description: `CBOM generated by cbom-js for ${projectName}`
    },
    properties: [
      { name: 'cbom-js:filesScanned',      value: String(scan.filesScanned) },
      { name: 'cbom-js:scanDuration',      value: `${scan.duration}ms` },
      { name: 'cbom-js:totalFindings',     value: String(scan.summary.total) },
      { name: 'cbom-js:criticalFindings',  value: String(scan.summary.critical) },
      { name: 'cbom-js:highFindings',      value: String(scan.summary.high) },
      { name: 'cbom-js:weakAlgorithms',    value: String(scan.summary.weak) },
      { name: 'cbom-js:quantumVulnerable', value: String(scan.summary.quantumVulnerable) },
      { name: 'cbom-js:sourcePath',        value: projectPath }
    ]
  };
}

// ── Component builder ─────────────────────────────────────────────────────────

function buildComponent(finding: CryptoFinding, rootPath: string): object {
  // All algorithm metadata comes from the registry — no local maps
  const meta = getAlgorithmMeta(finding.algorithm);

  // Registry provides primitive, cryptoFunctions, classicalSecurityLevel, oid
  const primitive            = meta.primitive            ?? 'other';
  const cryptoFunctions      = meta.cryptoFunctions      ?? [];
  const classicalSecurity    = meta.classicalSecurityLevel ?? 128;
  const oid                  = meta.oid;

  // RSA key size overrides classical security level
  const effectiveClassical = resolveClassicalSecurity(
    finding.algorithm,
    finding.keySize,
    classicalSecurity
  );

  const relativeLocation = finding.location.replace(rootPath + '/', '').replace(rootPath, '');

  return {
    type: 'cryptoAsset',
    'bom-ref': `crypto:${finding.algorithm.toLowerCase()}:${relativeLocation}:${finding.line}`,
    name: finding.algorithm,
    cryptoProperties: {
      assetType: 'algorithm',
      algorithmProperties: {
        primitive,
        ...(finding.mode    ? { mode: finding.mode.toLowerCase() }              : {}),
        ...(finding.keySize ? { parameterSetIdentifier: String(finding.keySize) } : {}),
        executionEnvironment: 'software',
        implementationPlatform: 'node.js',
        certificationLevel: ['none'],
        cryptoFunctions,
        nistQuantumSecurityLevel: finding.quantumSafe ? 1 : 0,
        classicalSecurityLevel: effectiveClassical
      },
      ...(oid ? { oid } : {})
    },
    evidence: {
      occurrences: [
        {
          location: relativeLocation,
          line: finding.line,
          ...(finding.column !== undefined ? { offset: finding.column } : {}),
          symbol: finding.algorithm
        }
      ]
    },
    properties: buildProperties(finding)
  };
}

function buildProperties(finding: CryptoFinding): object[] {
  const props: object[] = [
    { name: 'cbom-js:library',     value: finding.library },
    { name: 'cbom-js:weak',        value: String(finding.weak) },
    { name: 'cbom-js:quantumSafe', value: String(finding.quantumSafe) },
    { name: 'cbom-js:severity',    value: finding.severity }
  ];

  if (finding.cwe && finding.cwe.length > 0) {
    finding.cwe.forEach(c => props.push({ name: 'cbom-js:cwe', value: c }));
  }
  if (finding.notes) {
    props.push({ name: 'cbom-js:notes', value: finding.notes });
  }
  if (finding.context) {
    props.push({ name: 'cbom-js:codeSnippet', value: finding.context });
  }

  return props;
}

// ── Vulnerabilities ───────────────────────────────────────────────────────────

function buildVulnerabilities(findings: CryptoFinding[]): object[] {
  return findings
    .filter(f => f.weak || (f.cwe && f.cwe.length > 0))
    .filter(f => f.cwe && f.cwe.length > 0)
    .map(f => ({
      'bom-ref': `vuln:${f.algorithm}:${f.location}:${f.line}`,
      id: f.cwe![0],
      source: {
        name: 'CWE',
        url: `https://cwe.mitre.org/data/definitions/${f.cwe![0].replace('CWE-', '')}.html`
      },
      ratings: [
        { severity: f.severity.toLowerCase(), method: 'other' }
      ],
      // Description pulled from registry notes first, then finding notes, then derived
      description: buildVulnDescription(f),
      affects: [
        { ref: `crypto:${f.algorithm.toLowerCase()}:${f.location}:${f.line}` }
      ]
    }));
}

function buildVulnDescription(finding: CryptoFinding): string {
  // Registry notes take priority — no hardcoded algorithm-specific strings
  const meta = getAlgorithmMeta(finding.algorithm);
  if (meta.notes) return meta.notes;
  if (finding.notes) return finding.notes;

  // Generic fallback based on CWE — still not algorithm-specific hardcoding
  const cwe = finding.cwe?.[0];
  if (cwe === 'CWE-327') return `${finding.algorithm} is a weak or broken cryptographic algorithm`;
  if (cwe === 'CWE-326') return `${finding.algorithm} provides inadequate encryption strength and is vulnerable to quantum computing attacks`;
  if (cwe === 'CWE-338') return `${finding.algorithm} uses a non-cryptographic source of randomness`;
  if (cwe === 'CWE-321') return `${finding.algorithm} — hardcoded cryptographic key detected`;
  if (cwe === 'CWE-295') return `${finding.algorithm} — improper certificate validation`;
  if (cwe === 'CWE-347') return `${finding.algorithm} — improper verification of cryptographic signature`;

  return `Cryptographic issue detected: ${finding.algorithm}`;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

// RSA key size adjusts classical security level — this is math, not a lookup table
function resolveClassicalSecurity(
  algorithm: string,
  keySize: number | undefined,
  registryDefault: number
): number {
  if (!algorithm.toUpperCase().includes('RSA') || !keySize) {
    return registryDefault;
  }
  if (keySize < 2048)  return 0;    // broken
  if (keySize < 4096)  return 112;  // NIST minimum acceptable
  return 140;                        // 4096-bit RSA
}

function hasVulnerabilities(findings: CryptoFinding[]): boolean {
  return findings.some(f => f.weak || (f.cwe && f.cwe.length > 0));
}